### ISSUE TITLE
ookla speedtest-cli repositories have moved

### ISSUE THREAD

**Issue by davemuench** [qlustor/speedtest_ookla-to-influxdb#8]
If you redeploy your container and are only getting ping test results - no speedtest results - and see errors in the container logs about the speedtest program being missing, apparently ookla has moved to a new repository host. #7 fixes this.

Thanks for the container and dashboard!

**Comment by neurocis** [comment]
Merged. I will see about getting the docker hub updating as they no longer auto build for free.
